version: '3.4'

services:
  todoapi:
    #image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: TodoAPI\Dockerfile
    restart: unless-stopped
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
    ports:
      - "5000:8080"
      #- "5001:8081"

  todoapi_two:
    #image: ${DOCKER_REGISTRY-}todoapi_two
    build:
      context: .
      dockerfile: TodoAPI_Two\Dockerfile
    restart: unless-stopped
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
    ports:
      - "5005:8080"
      #- "5006:8081"

networks:
 default:
  name: nexus_neuron
  external: true
