name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
    #- name: Build the Docker image
    # run: docker build . --file Dockerfile --tag nexustodoapi:$(date +%s)
    -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/nexustodoapi:latest
